<a href="https://colab.research.google.com/github/rohit1308/google_collab_ML/blob/main/MLDEV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import sklearn

for name, mod in [("numpy", np), ("pandas", pd),
                  ("matplotlib", matplotlib), ("sklearn", sklearn)]:
    print(f"{name:<12} ok")
    #print(mod.__version__000000000)



numpy        ok
pandas       ok
matplotlib   ok
sklearn      ok


In [ ]:
#day 3 code
array=np.array([1,2,3]) #1 D just sequence of number,#1 hi dimension me 3 element
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.itemsize)
print(array.size)
a1=np.array([[1,2,3]])#1row 3column
print(a1.shape)
print(a1.ndim)

(3,)
1
int64
8
3
(1, 3)
2


In [ ]:
a=np.array([[1,2,3],[2,3,4]])
a.shape
a.ndim
a[1][2]

np.int64(4)

In [ ]:
a2=np.zeros((3,2))
a2.dtype,a.shape,a2

(dtype('float64'),
 (2, 3),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
ln=np.linspace(0,1,5)

ln

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
identity=np.eye(5)
identity,identity.shape,identity.ndim,identity.dtype

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 (5, 5),
 2,
 dtype('float64'))

In [ ]:
#creating random numbers


random_number=np.random.default_rng(4)
random_number.normal(5,1,4).round(3)


array([4.348, 4.825, 6.664, 5.659])

In [ ]:
#matrix reshape
m=np.ones(9)

m
m.reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#slicing operation on matrix
m=np.arange(12)
m=m.reshape(3,4)
print(m)
#print 4
print(m[1,2])
#all rows 1sr column
print(m[:,1])
#all columns last row
m[0:2,0:2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[1 5 9]


array([[0, 1],
       [4, 5]])

In [ ]:
#masking
m=np.arange(12)
m=m.reshape(3,4)
mask=m>6

#sum of mask

mask.sum()#sum of true statement

m[mask],mask,m>6,mask.sum()

(array([ 7,  8,  9, 10, 11]),
 array([[False, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True,  True]]),
 array([[False, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True,  True]]),
 np.int64(5))

In [ ]:
#masking with &
ages = np.array([23, 45, 17, 34, 12, 67])
incomes = np.array([30, 80, 0, 55, 0, 40])
print(ages[ages>18])
print(incomes[incomes>50])
mask=incomes>30
print(incomes[mask])
#now i want to know ages above 18 and income above 55
print(ages[(incomes>50) & (ages>=40)])

[23 45 34 67]
[80 55]
[80 55 40]
[45]


In [ ]:
from PIL import Image
image=Image.open("/content/IMG_5869.jpeg").transpose(Image.FLIP_TOP_BOTTOM)
image

FileNotFoundError: [Errno 2] No such file or directory: '/content/IMG_5869.jpeg'

In [ ]:
image_array=np.array(image)
image_array.shape

In [ ]:
image_array.dtype

In [ ]:
#increase brightness
#print(image_array)
#broadcast with 2 and convert above array into flaot
bright_array=np.clip(image_array.astype(np.float32)*0.5,0,255)
#convert array to image
bright_image=Image.fromarray(bright_array.astype(np.uint8))
bright_image


In [ ]:
image2=Image.open("/content/IMG_5869.jpeg").transpose(Image.FLIP_TOP_BOTTOM).convert("L")

#img2=np.array(Image.open("/content/IMG_589.png"))
blended=(img1 + image) / 2
blended_image=Image.fromarray(blended.astype(np.uint8))
#img1.shape,
blended_image

In [ ]:
imag=np.dot(image,image)